require 'pathname'
require 'tmpdir'

module CedarTargetSpecs
  UI_SPECS_TARGET_NAME = "Specs"
  CONFIGURATION = "Release"

  PROJECT_ROOT = Pathname.new(File.dirname(__FILE__)).parent.to_s
  BUILD_DIR = File.join(PROJECT_ROOT, "build")

  class << self
    def in_project_dir
      original_dir = Dir.pwd
      Dir.chdir(PROJECT_ROOT)

      yield

      ensure
      Dir.chdir(original_dir)
    end

    def deployment_target_sdk_version
      in_project_dir do
        `xcodebuild -showBuildSettings -target #{UI_SPECS_TARGET_NAME} | grep IPHONEOS_DEPLOYMENT_TARGET | awk '{print $3 }'`.strip
      end
    end

    def deployment_target_sdk_dir
      @sdk_dir ||= "#{xcode_developer_dir}/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator#{deployment_target_sdk_version}.sdk"
    end

    # Xcode 4.3 stores its /Developer inside /Applications/Xcode.app, Xcode 4.2 stored it in /Developer
    def xcode_developer_dir
      `xcode-select -print-path`.strip
    end

    def build_dir(effective_platform_name)
      File.join(BUILD_DIR, CONFIGURATION + effective_platform_name)
    end

    def is_run_unit_tests_deprecated?
      system("cat #{xcode_developer_dir}/Tools/RunUnitTests | grep -q 'RunUnitTests is obsolete.'")
    end

    def system_or_exit(cmd, stdout = nil)
      puts "Executing #{cmd}"
      cmd += " >#{stdout}" if stdout
      system(cmd) or raise "******** Build failed ********"
    end

    def run_cmd_and_grep_for_failure(cmd)
      puts "Executing #{cmd}"
      puts result = %x[#{cmd} 2>&1]
      if result.index(/Test Case.*failed/)
        exit(1)
      else
        exit(0)
      end
    end 

    def with_env_vars(env_vars)
      old_values = {}
      env_vars.each do |key,new_value|
        old_values[key] = ENV[key]
        ENV[key] = new_value
      end

      yield

      env_vars.each_key do |key|
        ENV[key] = old_values[key]
      end
    end

    def output_file(target)
      output_dir = if ENV['IS_CI_BOX']
        ENV['CC_BUILD_ARTIFACTS']
      else
        Dir.mkdir(BUILD_DIR) unless File.exists?(BUILD_DIR)
        BUILD_DIR
      end

      output_file = File.join(output_dir, "#{target}.output")
      puts "Output: #{output_file}"
      output_file
    end

    def kill_simulator
      system %Q[killall -m -KILL "gdb"]
      system %Q[killall -m -KILL "otest"]
      system %Q[killall -m -KILL "iPhone Simulator"]
    end
  end
end

desc "Clean build directory"
task :clean_Specs do
  CedarTargetSpecs.system_or_exit "rm -rf #{CedarTargetSpecs::BUILD_DIR}/*", CedarTargetSpecs.output_file("clean")
end

desc "Build Specs OCUnit application specs"
task :build_Specs => :clean_Specs do
  CedarTargetSpecs.kill_simulator
  CedarTargetSpecs.system_or_exit "pushd #{CedarTargetSpecs::PROJECT_ROOT} && xcodebuild -target BlindsidedStoryboard -configuration #{CedarTargetSpecs::CONFIGURATION} -sdk iphonesimulator#{CedarTargetSpecs.deployment_target_sdk_version} clean build ARCHS=i386 TEST_AFTER_BUILD=NO GCC_SYMBOLS_PRIVATE_EXTERN=NO SYMROOT='#{CedarTargetSpecs::BUILD_DIR}' && popd", CedarTargetSpecs.output_file("Specs-AppBuild")
  CedarTargetSpecs.system_or_exit "pushd #{CedarTargetSpecs::PROJECT_ROOT} && xcodebuild -target #{CedarTargetSpecs::UI_SPECS_TARGET_NAME} -configuration #{CedarTargetSpecs::CONFIGURATION} -sdk iphonesimulator#{CedarTargetSpecs.deployment_target_sdk_version} build ARCHS=i386 GCC_SYMBOLS_PRIVATE_EXTERN=NO TEST_AFTER_BUILD=NO SYMROOT='#{CedarTargetSpecs::BUILD_DIR}' && popd", CedarTargetSpecs.output_file("Specs-SpecBuild")
end

desc "Run Specs OCUnit application specs"
task :Specs => :build_Specs do
  if CedarTargetSpecs.is_run_unit_tests_deprecated?
    CedarTargetSpecs.run_cmd_and_grep_for_failure "pushd #{CedarTargetSpecs::PROJECT_ROOT} && xcodebuild test -scheme BlindsidedStoryboard -configuration #{CedarTargetSpecs::CONFIGURATION} -destination 'OS=#{CedarTargetSpecs.deployment_target_sdk_version},name=iPhone Retina (3.5-inch)' ARCHS=i386 SYMROOT='#{CedarTargetSpecs::BUILD_DIR}' && popd"
  else
    env_vars = {
      "DYLD_ROOT_PATH" => CedarTargetSpecs.deployment_target_sdk_dir,
      "DYLD_INSERT_LIBRARIES" => "#{CedarTargetSpecs.xcode_developer_dir}/Library/PrivateFrameworks/IDEBundleInjection.framework/IDEBundleInjection",
      "DYLD_FALLBACK_LIBRARY_PATH" => CedarTargetSpecs.deployment_target_sdk_dir,
      "XCInjectBundle" => "#{File.join(CedarTargetSpecs.build_dir("-iphonesimulator"), "#{CedarTargetSpecs::UI_SPECS_TARGET_NAME}.octest")}",
      "XCInjectBundleInto" => "#{File.join(CedarTargetSpecs.build_dir("-iphonesimulator"), "BlindsidedStoryboard.app/BlindsidedStoryboard")}",
      "IPHONE_SIMULATOR_ROOT" => CedarTargetSpecs.deployment_target_sdk_dir,
      "CFFIXED_USER_HOME" => Dir.tmpdir,
      "CEDAR_HEADLESS_SPECS" => "1",
      "CEDAR_REPORTER_CLASS" => "CDRColorizedReporter",
    }

    CedarTargetSpecs.with_env_vars(env_vars) do
      CedarTargetSpecs.run_cmd_and_grep_for_failure "#{File.join(CedarTargetSpecs.build_dir("-iphonesimulator"), "BlindsidedStoryboard.app/BlindsidedStoryboard")} -RegisterForSystemEvents -SenTest All"
    end
  end
end
